image: node:20

stages:
  - build
  - lint

.base:
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

variables:
  GIT_DEPTH: 0

format-check:
  stage: lint
  extends: .base
  script:
    - npx nx format:check --base=$NX_BASE --head=$NX_HEAD

type-check:
  stage: lint
  extends: .base
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t type-check --parallel=3

lint:
  stage: lint
  extends: .base
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint --parallel=3

build:
  stage: build
  extends: .base
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
