image: registry.gitlab.com/mccarronea/pf2e-companion/ci-runner

stages:
  - setup
  - lint
  - build
  - publish
  - e2e

.npm:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
    policy: pull
  before_script:
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}
    - echo "Determining affected scopes from head $NX_HEAD and base $NX_BASE"
    - npm ci --cache .npm --prefer-offline

.lint:
  extends: .npm
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

.build:
  extends: .npm
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always

.publish:
  stage: publish
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  image:
    name: gcr.io/kaniko-project/executor:v1.18.0-debug
    entrypoint: ['']

.e2e:
  extends: .npm
  stage: e2e
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  variables:
    FF_NETWORK_PER_BUILD: 'true'
    PORT: '4000'
    ADDRESS: '0.0.0.0'
    DB_HOST: 'db'
    DB_PORT: '27017'
    COMPENDIUM_API_URL: 'http://compendium-api:4000'
  services:
    - name: '$CI_REGISTRY_IMAGE/db:latest'
      alias: db
    - name: '$CI_REGISTRY_IMAGE/compendium-api:latest'
      alias: compendium-api
      entrypoint: ['node', 'main.js']

install-dependencies:
  stage: setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - package-lock.json
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
    policy: pull-push
  script: npm ci --cache .npm --prefer-offline

format-check:
  extends: .lint
  script:
    - npm run format:check

type-check:
  extends: .lint
  script:
    - npx nx affected -t type-check --base=$NX_BASE --head=$NX_HEAD --parallel=6

lint:
  extends: .lint
  script:
    - npx nx affected -t lint --base=$NX_BASE --head=$NX_HEAD --parallel=6

build:
  extends: .build
  artifacts:
    paths:
      - dist/
  script:
    - npx nx affected -t build --base=$NX_BASE --head=$NX_HEAD --parallel=6

# Hopefully gitlab will support rules for artifacts soon so this stage can be conditionally skipped
# (issue here: https://gitlab.com/gitlab-org/gitlab/-/issues/215100)
publish:compendium-api:
  extends: .publish
  script:
    - '[[ -d dist/apps/compendium-api ]] && /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/apps/compendium-api/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/compendium-api:latest"
      || exit 0'

e2e:compendium-api:
  extends: .e2e
  script:
    - npx nx affected -t ci:api-e2e --base=$NX_BASE --head=$NX_HEAD
# These e2e tests take too long and use too many compute resources to run on every MR
# I will eventually run these only on automated deployment pipeline
# e2e:ff:
#   extends: .e2e
#   script:
#     - npx nx affected -t ci:frontend-e2e --base=$NX_BASE --head=$NX_HEAD --browser firefox

# e2e:chrome:
#   extends: .e2e
#   script:
#     - npx nx affected -t ci:frontend-e2e --base=$NX_BASE --head=$NX_HEAD --browser chrome

# e2e:edge:
#   extends: .e2e
#   script:
#     - npx nx affected -t ci:frontend-e2e --base=$NX_BASE --head=$NX_HEAD --browser edge
