export const skillLabels = {
  acr: 'Acrobatics',
  arc: 'Arcana',
  ath: 'Athletics',
  cra: 'Crafting',
  dec: 'Deception',
  dip: 'Diplomacy',
  itm: 'Intimidation',
  lor: 'Lore',
  med: 'Medicine',
  nat: 'Nature',
  occ: 'Occultism',
  prf: 'Performance',
  rel: 'Religion',
  soc: 'Society',
  ste: 'Stealth',
  sur: 'Survival',
  thi: 'Thievery',
};
